#!/usr/bin/env node
/**
 * fix-c5.mjs — Replaces leaked case-summary cells with step-local expected results.
 * Each entry: [relPath, leaked, fix]
 * Uses string.replace (first occurrence) so leaked text must be unique within each file's step rows.
 * TC-LOC-LGL-016/017 share the same leaked text; both are replaced by calling replace() twice.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = 'C:\\Users\\RutvikKhorasiya\\projects\\encore_framework';
const BASE = 'clients/encore/specs_planning/test-cases/setup';

const FIXES = [
  // ── corporate_override_core ──────────────────────────────────────────────
  ['corporate-override/corporate_override_core_test_cases.md',
    'Toggling the Active checkbox flips its state and dirties the form (Save enables). (No commit.)',
    'The Save button is now enabled.'],

  // ── corporate_override_nm2268 ────────────────────────────────────────────
  ['corporate-override/corporate_override_nm2268_test_cases.md',
    'A non-Revenue-Management user cannot edit Override cells, trigger Save, or access Import. The grid renders in read-only mode (Revenue Management role required for edit access).',
    'The Import button is absent or disabled.'],

  // ── corporate_override_nm2273 ────────────────────────────────────────────
  ['corporate-override/corporate_override_nm2273_test_cases.md',
    'A non-numeric price is rejected with a message that the Override Price must be a decimal within two decimal places; the grid is unchanged. (This is a parse-level rejection surfaced as an alert, distinct from the body-level semantic rejections.)',
    'After reloading, the grid still shows the original values; the invalid price was not persisted.'],

  // ── corporate_pricing_strategy ───────────────────────────────────────────
  ['corporate-pricing/corporate_pricing_strategy_test_cases.md',
    'Add ("+") opens the New Pricing Strategy dialog; submitting "Add" appends a fresh (unsaved) strategy to the list. (The add flow opens a dialog first.)',
    'The strategy is removed from the list; no changes are committed.'],

  // ── locations_account_address (24) ───────────────────────────────────────
  ['locations/locations_account_address_test_cases.md',
    'Two distinct cards visible with correct section headers',
    'Two side-by-side cards are visible: the left card is "Venue/Branch Account" and the right card is "Master Bill To Address".'],
  ['locations/locations_account_address_test_cases.md',
    'Account List dialog opens with search filters and result table',
    'The dialog title reads "Account List", the expected search filters are present, and the results table is visible.'],
  ['locations/locations_account_address_test_cases.md',
    'Select button only enables after a row is checked via row checkbox',
    'The Select button is now enabled.'],
  ['locations/locations_account_address_test_cases.md',
    'Cancel dismisses dialog without updating the Name field',
    'The Name textbox still shows "Parker Palm Springs"; the dialog closed without updating the field.'],
  ['locations/locations_account_address_test_cases.md',
    'Reset clears all filter inputs and results table',
    'All search fields are empty and the results table shows no results.'],
  ['locations/locations_account_address_test_cases.md',
    'Select Customer Address dialog opens with 7 address records (Total Addresses: 7 in footer)',
    'The dialog title reads "Select Customer Address", the expected columns and buttons are present, and the footer shows "Total Addresses: 7".'],
  ['locations/locations_account_address_test_cases.md',
    'Select button only enables when a row checkbox is checked',
    'The Select button is now enabled.'],
  ['locations/locations_account_address_test_cases.md',
    'Search bar filters the visible rows instantly as you type; "Beverly" matches 1 of 7 addresses',
    'Exactly one row containing "Beverly" is displayed and the footer row is still visible.'],
  ['locations/locations_account_address_test_cases.md',
    'Save button remains disabled regardless of row selection (no create-address function)',
    'The Save button is still disabled.'],
  ['locations/locations_account_address_test_cases.md',
    'Both Venue and Master Address buttons open the same Select Customer Address dialog',
    'The same Select Customer Address dialog opens, showing the same 7 address rows with "Total Addresses: 7" in the footer.'],
  ['locations/locations_account_address_test_cases.md',
    'City, State, Zip, Country in Venue section are display-only; no edit controls',
    'The City, State, Zip, and Country fields in the Venue card show the correct values as static text with no edit controls.'],
  ['locations/locations_account_address_test_cases.md',
    'City, State, Zip, Country in Master Bill To Address are display-only (cannot be typed into directly)',
    'The City, State, Zip, and Country fields in the Master Bill To Address card show the correct values as static text.'],
  ['locations/locations_account_address_test_cases.md',
    'Phone 2 has no required validation; empty is valid',
    'The Phone 2 field shows no error message and is not marked invalid.'],
  ['locations/locations_account_address_test_cases.md',
    'Save button starts disabled (no unsaved changes)',
    'The left-panel Save button is disabled.'],
  ['locations/locations_account_address_test_cases.md',
    'Editing any field triggers unsaved-change state and enables Save',
    'The Save button is now enabled.'],
  ['locations/locations_account_address_test_cases.md',
    'Save requires confirmation -- confirmed save disables Save button',
    'The Save button is disabled; the form is in a clean saved state.'],
  ['locations/locations_account_address_test_cases.md',
    'Saved data persists after full page reload',
    'Phone 2 shows the previously saved value and the Save button is disabled.'],
  ['locations/locations_account_address_test_cases.md',
    'Cancel in Save Changes dialog dismisses without persisting; unsaved changes remain',
    'The page reloads with the original field values; the unsaved change is not present.'],
  ['locations/locations_account_address_test_cases.md',
    'Clearing Phone 1 shows validation indicators but does NOT disable Save',
    'The page reloads and Phone 1 is restored to its original value.'],
  ['locations/locations_account_address_test_cases.md',
    'Address filter returns accounts with matching address',
    'The Account List dialog closes.'],
  ['locations/locations_account_address_test_cases.md',
    'City filter returns accounts with matching city',
    'The Account List dialog closes.'],
  ['locations/locations_account_address_test_cases.md',
    'An optional field (Phone 2) can be cleared and the empty value persists through save + reload',
    'Phone 2 is empty; the cleared value persisted through save and reload.'],
  ['locations/locations_account_address_test_cases.md',
    'The Account Number filter (the 4th text filter) returns the matching account',
    'The Account List dialog closes.'],
  ['locations/locations_account_address_test_cases.md',
    'Clearing the Address dialog\'s search restores the full unfiltered row set',
    'The Account List dialog closes.'],

  // ── locations_left_panel_basic_information (25) ──────────────────────────
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'All fields display their expected default values in correct enabled/disabled state for location 1604',
    'Enable Productions Orders is checked and disabled.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Office field is permanently read-only; cannot be clicked or edited',
    'No cursor or editing interaction is possible in the Office field.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Local Office field is permanently read-only',
    'The field value cannot be changed.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'eCommerce Active is permanently checked and non-interactive',
    'The eCommerce Active checkbox remains checked regardless of other field changes.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Enable Productions Orders is permanently checked and non-interactive',
    'Enable Productions Orders remains checked throughout the session.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Save button is disabled on fresh load because there are no unsaved changes',
    'No form changes have been made; the page is in a clean state.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Save enables as soon as any field is changed; reverting the change back to its original value results in no net change, so Save returns to DISABLED',
    'Save returns to disabled when Union is reverted to its original value; no net change is detected.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Active checkbox state persists through save-reload cycle in both checked and unchecked states',
    'After reloading, Active shows checked; the saved state persisted.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Tax Mode shows exactly 2 options: US, International',
    'The dropdown closes when Escape is pressed.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Country contains exactly 4 options: United States, Mexico, Canada, Bahamas',
    'The dropdown closes.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'The Region dropdown offers its full set of region options; the current value for this location is "Palm Springs"; selecting a different region updates the field immediately',
    'After reloading without saving, Region reverts to "Palm Springs".'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'The "Servicing Branch Office" dropdown contains a large list of branch office options; no branch office is currently selected for this location; selecting any option enables Save and satisfies the required field validation',
    'The selected option appears in the field and Save becomes enabled.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Changing country clears Tax Mode (shows error) and Region; Save becomes disabled because Tax Mode is empty',
    'The Save button is disabled because Tax Mode is now empty.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Save is disabled when Tax Mode is empty; selecting a Tax Mode value re-enables Save (if no other disable conditions present)',
    'Changing Country again clears Tax Mode and Save returns to disabled.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Switching country back to United States does NOT auto-restore Tax Mode or Region; manual re-selection required every time country changes',
    'Region remains empty after switching back to United States.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Enable Job Costing is USA-only; changing to non-USA country automatically unchecks it in Local Information tab',
    'Enable Job Costing is now unchecked after changing to a non-USA country.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Remit PST Tax is a Canada-specific field; only appears in Local Information tab when Country = Canada',
    'The Remit PST Tax checkbox appears and is checked by default after setting Country to Canada.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Local Office Name change persists across save+reload; restored to default afterward (no state leak)',
    'The name is restored to "Parker Palm Springs" and saved successfully.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Tax Mode change persists across save+reload; restored to default (no state leak)',
    'Tax Mode is restored to "US" and saved successfully.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Region change persists across save+reload; restored to default (no state leak)',
    'Region is restored to "Palm Springs" and saved successfully.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Clicking the Pay To Address label opens the "Pay To List" search dialog with 5 filters, Search/Reset, a results table, and Select/Cancel',
    'The footer shows a disabled Select button and a Cancel button.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Select enables only after a row checkbox is checked (single-select)',
    'The Select button becomes enabled.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Cancel dismisses the dialog without applying any selection; the form has no unsaved changes',
    'The Pay To Address display still shows "Encore" and Save stays disabled; Cancel made no changes.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Reset clears all filters and restores the full unfiltered Pay To list (with no leftover changes)',
    'All filters are cleared and the full unfiltered Pay To list is restored.'],
  ['locations/locations_left_panel_basic_information_test_cases.md',
    'Selecting a Pay To via the dialog updates the display field and dirties the form (Save enables); reloading without saving discards the change',
    'After reloading without saving, the Pay To display reverts to "Encore".'],

  // ── locations_legal (12) ─────────────────────────────────────────────────
  ['locations/locations_legal_test_cases.md',
    'US English row shows: Language Name = "US English", Service Charge Name = "Resort Service Charge", Terms and Conditions Name = "LDW"',
    'The third cell in the US English row shows a combobox with "LDW" selected.'],
  ['locations/locations_legal_test_cases.md',
    'Language Name column is read-only static text, no editing possible',
    'The first column cell contains static text with no interactive element.'],
  ['locations/locations_legal_test_cases.md',
    'Dropdown opens with 114 service charge options; currently selected option "Resort Service Charge" is visually indicated; Escape closes dropdown without changing value',
    'The dropdown closes and the value remains unchanged.'],
  ['locations/locations_legal_test_cases.md',
    'Dropdown opens with 50 T&C options; currently selected "LDW" is visually indicated; Escape closes without changing value',
    'The dropdown closes and the value remains unchanged.'],
  ['locations/locations_legal_test_cases.md',
    'Neither dropdown has a search/filter input -- all options are rendered in a flat list',
    'The dropdown closes.'],
  ['locations/locations_legal_test_cases.md',
    'Left-panel Save button is disabled when no changes have been made to any field on the page',
    'The left-panel Save button is disabled.'],
  ['locations/locations_legal_test_cases.md',
    'Changing Service Charge Name enables the shared left-panel Save button',
    'The left-panel Save button is now enabled.'],
  ['locations/locations_legal_test_cases.md',
    'Changing T&C Name enables the shared left-panel Save button',
    'The left-panel Save button is now enabled.'],
  ['locations/locations_legal_test_cases.md',
    'Clicking Cancel in Save Changes dialog dismisses dialog without saving; original values persist after reload',
    'Service Charge Name still shows "Resort Service Charge"; the cancelled change was not persisted.'],
  ['locations/locations_legal_test_cases.md',
    'Unsaved Legal changes trigger the browser\'s leave-page confirmation when there are unsaved changes and the user attempts to navigate away',
    'The page reloads and the changes are discarded.'],
  // TC-LOC-LGL-016 AND TC-LOC-LGL-017 share the same leaked text — replace() called twice below
  ['locations/locations_legal_test_cases.md',
    'Options are sorted alphabetically',
    'The options are in alphabetical order.'],
  ['locations/locations_legal_test_cases.md',
    'Options are sorted alphabetically',
    'The options are in alphabetical order.'],

  // ── locations_notes (21) ─────────────────────────────────────────────────
  ['locations/locations_notes_test_cases.md',
    'Empty table ("No Notes Available"), counter at 0/4000, Add button enabled, NO Delete button, NO column headers',
    'No Delete button appears in the Notes section.'],
  ['locations/locations_notes_test_cases.md',
    'Counter updates in real time to 25/4000; Save button enables on change',
    'The left-panel Save button is enabled.'],
  ['locations/locations_notes_test_cases.md',
    'Delete appears on typed rows and on ALL rows when 2+ exist; counter adds +1 delimiter per additional row',
    'The counter shows "11/4000".'],
  ['locations/locations_notes_test_cases.md',
    'Each additional row adds exactly 1 delimiter character to the total count',
    'The counter shows "15/4000" after adding "End" to the third row.'],
  ['locations/locations_notes_test_cases.md',
    'Counter decreases by deleted row text + delimiter; Delete stays on the first row because it has content',
    'Only one row remains, showing "First note", and the Delete button is still present.'],
  ['locations/locations_notes_test_cases.md',
    'Progress bar fills proportionally to character usage against the 4000 limit',
    'The progress bar width corresponds proportionally to the character usage percentage.'],
  ['locations/locations_notes_test_cases.md',
    'Keyboard input is blocked at 4000 characters; pasting bypasses the limit (it is a soft limit); the counter shows the overage; the field has no hard maximum-length cap',
    'The pasted content is accepted beyond 4000 characters; there is no hard browser maximum-length cap.'],
  ['locations/locations_notes_test_cases.md',
    'HTML entities, quotes, accented chars accepted, counted, saved, retrieved without corruption',
    'After reloading and opening Notes, the special characters are preserved exactly as typed.'],
  ['locations/locations_notes_test_cases.md',
    'Remaining rows shift; content preserved; counter decreases correctly',
    'The counter decreased by 6 characters (5 for "Row B" plus 1 delimiter).'],
  ['locations/locations_notes_test_cases.md',
    'Empty row has no Delete; Delete appears immediately when text is typed (even 1 char)',
    'The Delete button appears on the row.'],
  ['locations/locations_notes_test_cases.md',
    'XSS payload stored and retrieved as plain text; never executed as HTML or JavaScript',
    'After reloading, the script tag is displayed as literal text with no script execution.'],
  ['locations/locations_notes_test_cases.md',
    'SQL injection payload stored and retrieved as plain text; no database side effects',
    'The SQL payload is displayed as literal text with no database errors or missing data.'],
  ['locations/locations_notes_test_cases.md',
    'Multi-byte unicode and emoji preserved without corruption through the full save+reload cycle',
    'After reloading, the multi-byte content is preserved exactly as typed.'],
  ['locations/locations_notes_test_cases.md',
    'Counter shows the overage; there is no hard maximum-length cap to prevent pasting; the counter shows "N/4000(0 Left)" for any N at or above 4000',
    'The field accepts the pasted content; the counter shows the overage and there is no hard maximum-length cap.'],
  ['locations/locations_notes_test_cases.md',
    'All three notes you entered remain after saving and reloading, with the correct text and order. (The app keeps one extra empty row at the end, so check the text of your notes rather than the total number of rows.)',
    'All note rows are cleared and the save completes successfully.'],
  ['locations/locations_notes_test_cases.md',
    'Full 4000-char content persists after save+reload without truncation',
    'The row is deleted and the save completes successfully.'],
  ['locations/locations_notes_test_cases.md',
    'Cancelling save dialog prevents persistence; note is discarded on reload',
    'After reloading, the Notes tab shows "No Notes Available"; the note was not persisted.'],
  ['locations/locations_notes_test_cases.md',
    'Both notes persist after two sequential saves with a reload between saves (a reload is required between saves because, in a post-save session, the Save button stays disabled after adding and filling a new note until the page is reloaded)',
    'Two rows are present: the first reads "Sequential A" and the second reads "Sequential B".'],
  ['locations/locations_notes_test_cases.md',
    'In-place edit of a saved note persists after a second save and reload (a reload is required between saves because, in a post-save session, the Save button stays disabled after filling the note until the page is reloaded)',
    'The first row reads "Edited text".'],
  ['locations/locations_notes_test_cases.md',
    'An empty row saved deliberately persists as an empty note box, distinct from the "No Notes Available" default state',
    'The counter shows 0 and "No Notes Available" is not shown; an empty note box is present.'],
  ['locations/locations_notes_test_cases.md',
    'Content exceeding the 4000 soft limit persists without the text being shortened',
    'The counter shows 4001 and the text length is 4001.'],

  // ── locations_shared_setup_locations (37) ────────────────────────────────
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Tab renders table with 5-column layout and Add button at bottom',
    'The Add button is visible in the last row and is enabled.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    '5 columns with headers "Local Office", "Local Office Name", "Primary Office", "Shares Inventory", and one empty header',
    'The five column headers appear in the correct order: Local Office, Local Office Name, Primary Office, Shares Inventory, and one empty actions column.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Self-location (1604) row: Primary Office locked-checked, Shares Inventory editable-unchecked, Delete disabled',
    'The Delete button is disabled for the self-location row.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Primary Office cannot be unchecked for the self-location; clicking it has no effect because the checkbox is disabled',
    'The Primary Office checkbox is still checked; clicking it had no effect.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Delete button is disabled for self-location; self-row cannot be removed',
    'Clicking Delete produces no action; the row remains in the table.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Toggling Shares Inventory marks form as dirty, enables left-panel Save',
    'The left-panel Save button is enabled.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Checked state persists after save + reload',
    'The Shares Inventory checkbox for row 1604 is still checked.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Search input filters results table by location name substring match',
    'The search dialog closes.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Search input filters results table by location number match',
    'The search dialog closes.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Selecting a row checkbox enables the Select button',
    'The Select button is now enabled.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Selecting a location and clicking Select adds it to the table and Save becomes enabled',
    'The left-panel Save button is enabled; unsaved changes are present.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Non-self rows: Primary Office disabled+unchecked, Shares Inventory checked+editable, Delete enabled',
    'The Delete button is enabled for the non-self location row.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Delete immediately removes the non-self row without any confirmation dialog',
    'The left-panel Save button is still enabled; unsaved changes remain from the add and delete cycle.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Cancelling dialog after selecting a row makes no changes to the table',
    'The left-panel Save button is disabled; cancelling made no changes.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'No dedicated Save inside this tab; save uses left-panel Save with "Save Changes" confirmation dialog',
    'The save dialog is confirmed and changes are saved successfully.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Added location persists after save + reload round-trip',
    'The table has 2 rows and the added location data is correct.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Non-self Shares Inventory toggle persists after save + reload',
    'After reloading, the non-self Shares Inventory checkbox is unchecked.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Deleted location stays removed after save + reload',
    'After reloading, only the self-row (1604) remains.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Multiple changes (self SI toggle + add location) persist together',
    'After reloading, Shares Inventory is checked and the added row is present.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Cancelling the Save dialog does NOT persist changes',
    'After reloading without saving, Shares Inventory reverts to unchecked.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Unsaved changes trigger the browser\'s leave-page confirmation on navigation/reload',
    'The page remains after dismissing the dialog.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Dialog excludes locations already associated with this office',
    'The previously added location is absent from the dialog results.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Each of the 5 column headers is addressed and verified individually',
    'The actions column header is visible.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Number-search "1233" returns exactly one row for the Miami Marriott Biscayne Bay office',
    'The search dialog closes.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    '1-char search filter renders ≥1 row in dialog; no form leak after cancel + reload',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    '200-char paste does not break dialog rendering; either 0 results or "No results." cleanly',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Clearing the search input restores the unfiltered row count; baseline is bulk catalog (~3000+)',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Special chars produce either zero real rows or "No results." placeholder; no crash, Select stays disabled',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Whitespace-only input either treats as empty (full bulk) or shows "No results."; no crash',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Filter trims (or doesn\'t) whitespace consistently; Atlanta rows render',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Re-typing replaces previous filter; final state shows Boston rows, not Atlanta',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Clearing input via clear restores rows to bulk count (catalog ~3000+ post-filter)',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Deleting middle row preserves rows 0 and 2 across save+reload',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Bulk-delete of all non-self rows persists; baseline 1-row state restored after save+reload',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Toggling non-self SI does NOT affect self SI across the save+reload cycle (cross-row save independence)',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    '5-row boundary push persists across save+reload',
    'The table is restored to a clean state.'],
  ['locations/locations_shared_setup_locations_test_cases.md',
    'Toggling non-self SI does NOT change self SI in-page (pre-save assertion)',
    'The table is restored to a clean state.'],
];

// Group by file, apply replacements
const byFile = new Map();
for (const [rel, leaked, fix] of FIXES) {
  if (!byFile.has(rel)) byFile.set(rel, []);
  byFile.get(rel).push([leaked, fix]);
}

let totalReplaced = 0;
for (const [rel, pairs] of byFile) {
  const fp = join(ROOT, BASE, rel);
  let content = readFileSync(fp, 'utf8');
  let fileReplaced = 0;
  for (const [leaked, fix] of pairs) {
    const old = `| ${leaked} |`;
    const neu = `| ${fix} |`;
    if (!content.includes(old)) {
      console.error(`MISS in ${rel}:\n  old: ${old.slice(0, 100)}`);
      continue;
    }
    content = content.replace(old, neu);
    fileReplaced++;
  }
  writeFileSync(fp, content, 'utf8');
  console.log(`${rel.split('/').pop()}: ${fileReplaced} replacements`);
  totalReplaced += fileReplaced;
}
console.log(`\nTotal replacements applied: ${totalReplaced}`);
