export const SetupLocalInfoSelectors = {
  btnSaveLocalInfo: '[data-testid="location-settings-btn-save"]',
  toastLocalInfoUpdated: 'li:has-text("Local information updated")',

  spinLDWPercentage: '[data-testid="location-settings-input-default-ldw-percentage"]',
  spinCCPercentage: '[data-testid="location-settings-input-cables-consumables-percentage"]',
  spinETSPercentage: '[data-testid="location-settings-input-ets-percentage"]',
  spinResortTaxPercentage: '[data-testid="location-settings-input-resort-tax-percent"]',
  spinSetStrikeLaborBillingGoal: '[data-testid="location-settings-input-set-strike-labor-billing"]',
  spinThreshold: '[data-testid="location-settings-input-threshold-amount"]',

  txtOracleProduct: '[data-testid="location-settings-input-oracle-product"]',
  txtOracleDepartment: '[data-testid="location-settings-input-oracle-dept"]',

  errValidationMessage: 'p:has-text("Number must be")',
  errMinBoundary: 'p:has-text("Number must be greater than or equal to 0")',
  errMaxBoundary: 'p:has-text("Number must be less than or equal to 100")',

  chkApplyLDW: '[data-testid="location-settings-checkbox-apply-ldw"]',
  chkCalculateLDWonNetAmount: '[data-testid="location-settings-checkbox-calc-ldw-on-net-amount"]',
  chkApplyCablesConsumablesFee: '[data-testid="location-settings-checkbox-apply-cables-consumables"]',
  chkCalculateCConNetAmount: '[data-testid="location-settings-checkbox-calc-cac-on-net-amount"]',
  chkEnableMultidayPricing: '[data-testid="location-settings-checkbox-enable-multiday-pricing"]',
  chkAllowETS: '[data-testid="location-settings-checkbox-allow-ets"]',
  chkServiceCharge: '[data-testid="location-settings-checkbox-allow-service-charge"]',
  chkShowServiceChargeAsAdministrativeFee: '[data-testid="location-settings-checkbox-is-administrative-fee"]',
  chkCalculateServiceChargeOnNetAmount: '[data-testid="location-settings-checkbox-calc-service-charge-on-net"]',
  chkAllowResortTax: '[data-testid="location-settings-checkbox-allow-resort-tax"]',
  chkTickerCalc: '[data-testid="location-settings-checkbox-allow-tick-calc"]',
  chkEnableSetStrikeLaborMinutes: '[data-testid="location-settings-checkbox-enable-set-strike-minutes"]',
  chkApplySetStrikeLaborMinutes: '[data-testid="location-settings-checkbox-apply-set-strike-minutes"]',
  chkInternetAssetReservation: '[data-testid="location-settings-checkbox-allow-internet-asset-reservation"]',
  chkAllowDPCD: '[data-testid="location-settings-checkbox-allow-dpcd"]',
  chkExcludeImpliedDiscount: '[data-testid="location-settings-checkbox-exclude-implied-discount"]',
  chkPromptForApproval: '[data-testid="location-settings-checkbox-prompt-for-approval"]',
  chkCreditMemoApprovalRequired: '[data-testid="location-settings-checkbox-credit-memo-approval"]',
  chkEnableDiscountReason: '[data-testid="location-settings-checkbox-check-discount"]',
  chkUseESignature: '[data-testid="location-settings-checkbox-use-esign"]',
  chkEnableProductGroup: '[data-testid="location-settings-checkbox-enable-product-group"]',
  chkAllowProductionQuote: '[data-testid="location-settings-checkbox-allow-production-quote"]',
  chkSuppressDayRateDiscount: '[data-testid="location-settings-checkbox-suppress-discount"]',

  rdoBillingTypeMaster: '[data-testid="location-settings-input-billing-type"] button[role="radio"][value="true"]',
  rdoBillingTypeDirect: '[data-testid="location-settings-input-billing-type"] button[role="radio"][value="false"]',
  rdoBillingWayEvent: '[data-testid="location-settings-input-billing-way"] button[role="radio"][value="true"]',
  rdoBillingWayDaily: '[data-testid="location-settings-input-billing-way"] button[role="radio"][value="false"]',

  btnEffectiveDate: '[data-testid="location-settings-btn-effective-date"]',
  drpBillingCycle: '[data-testid="location-settings-select-billing-cycle"]',
  chkWarehouseBilling: '[data-testid="location-settings-checkbox-warehouse-billing"]',
  drpOracleOrganization: '[data-testid="location-settings-select-oracle-org"]',
  chkCompassIntegration: '[data-testid="location-settings-checkbox-compass-integration"]',
  chkCompanyRemitTax: '[data-testid="location-settings-checkbox-company-remit-tax"]',
  chkDisplayTax: '[data-testid="location-settings-checkbox-display-tax"]',
  chkCommReceiver: '[data-testid="location-settings-checkbox-comm-receiver"]',
  chkEnableIDCBilling: '[data-testid="location-settings-checkbox-enable-idc-billing"]',
  chkSkipBilling: '[data-testid="location-settings-checkbox-skip-billing"]',
  chkSeparateMasterBillCommissionInvoice: '[data-testid="location-settings-checkbox-separate-commission-invoice"]',
  chkShowSubRental: '[data-testid="location-settings-checkbox-show-sub-rental"]',
  chkInventoryOnly: '[data-testid="location-settings-checkbox-inventory-only"]',
  chkIntercompany: '[data-testid="location-settings-checkbox-intercompany"]',
  chkCalculateCommissionTax: '[data-testid="location-settings-checkbox-calculate-commission-tax"]',
  chkCanCreateExternalCustomerLink: '[data-testid="location-settings-checkbox-can-create-external-link"]',
  chkOffsiteEventLocation: '[data-testid="location-settings-checkbox-offsite-event-location"]',
  chkExhibitShowRate: '[data-testid="location-settings-checkbox-exhibit-show-rate"]',
  chkEnableJobCosting: '[data-testid="location-settings-checkbox-enable-job-costing"]',
  chkEnableDiscountGuidance: '[data-testid="location-settings-checkbox-discount-guidance"]',
  chkEnableProposal: '[data-testid="location-settings-checkbox-enable-proposal"]',
  chkHRIRemitTax2: 'dt:has-text("HRI Remit Tax 2") + dd button[role="checkbox"]',
} as const;
