import * as fs from 'fs';
import * as path from 'path';
import type {
  Reporter,
  TestCase,
  TestResult,
  FullResult,
} from '@playwright/test/reporter';
import {
  FailureCategory,
  type NetworkFailure,
  type ConsoleEntry,
  type AuthChainEntry,
  type DiagnosticSnapshot,
  type UrlBreadcrumb,
  type TriageResult,
} from '../framework-contracts/diagnostics';

export interface FailureEntry {
  testName: string;
  file: string;
  error: string;
  fullError: string;
  selector: string | null;
  duration: number;
  screenshotPath: string | null;
  tracePath: string | null;
  lastActions: string[];
  failureCategory: FailureCategory;
  pageUrl: string;
  workerIndex: number;
  retryAttempt: number;
  consoleErrors: ConsoleEntry[];
  networkFailures: NetworkFailure[];
  pageErrors: string[];
  authChain: AuthChainEntry[];
 /** First 10KB of DOM at failure time -- agent gets DOM context without opening files. */
  domSnippet: string;
 /** Full navigation breadcrumbs from diagnostics. */
  urlBreadcrumbs: UrlBreadcrumb[];
 /** Triage result from Healer Phase 0 (populated post-triage, null initially). */
  triage: TriageResult | null;
 /** Bug report ID if triage = BUG (e.g., ""). */
  bugReportId: string | null;
 /** Detailed bug hunt category from classifier (populated by Healer post-triage, null initially). */
  bugHuntCategory: string | null;
 /** Test-ID status: PRESENT/MISSING/CHANGED (populated by Healer post-triage, null initially). */
  testIdStatus: string | null;
 /** Feature change magnitude: SMALL/BIG (populated by Healer post-triage, null initially). */
  changeSize: string | null;
 /** How many times this test has failed in recent runs (from reports/failure-history.json). */
  failureCount: number;
}

interface FailureSummary {
  timestamp: string;
  failures: FailureEntry[];
  passed: number;
  failed: number;
  fixme: number;
  totalDuration: number;
 /** Triage classification stats (populated after Healer Phase 0). */
  triageStats: { bugs: number; featureChanges: number; testDefects: number; uncertain: number } | null;
 /** Paths to bug report JSON files generated by Healer. */
  bugReportFiles: string[];
}

const OUTPUT_FILE = path.join(process.cwd(), 'reports', '');
const FAILURE_HISTORY_FILE = path.join(process.cwd(), 'reports', 'failure-history.json');

/**
 * Read reports/failure-history.json and count entries matching the given test name.
 * Returns 0 if the file doesn't exist or is malformed.
 */
function getFailureCount(testName: string): number {
  try {
    if (!fs.existsSync(FAILURE_HISTORY_FILE)) return 0;
    const raw = fs.readFileSync(FAILURE_HISTORY_FILE, 'utf-8');
    const history = JSON.parse(raw);
    if (!Array.isArray(history)) return 0;
    return history.filter(
      (entry: { testName?: string }) => entry.testName === testName,
    ).length;
  } catch {
    return 0;
  }
}

/** Known selector prefixes for extraction. */
const SELECTOR_PREFIXES = ['btn', 'txt', 'drp', 'chk', 'lnk', 'rdo', 'dlg', 'tbl', 'err', 'col', 'spin', 'tab', 'pnl'];

class AgentReporter implements Reporter {
  private failures: FailureEntry[] = [];
  private passedCount = 0;
  private failedCount = 0;
  private fixmeCount = 0;
  private totalDuration = 0;

  onTestEnd(test: TestCase, result: TestResult): void {
    this.totalDuration += result.duration;

    if (result.status === 'skipped') {
 // Count fixme/skipped tests
      const annotations = test.annotations || [];
      const isFixme = annotations.some(a => a.type === 'fixme');
      if (isFixme) this.fixmeCount++;
      return;
    }

    if (result.status === 'passed' || result.status === 'timedOut' && result.errors.length === 0) {
      this.passedCount++;
      return;
    }

    if (result.status === 'failed' || result.status === 'timedOut') {
      this.failedCount++;

      const fullErrorMsg = result.errors
        .map(e => e.message || e.stack || 'Unknown error')
        .join(' | ');

 // Backward-compatible truncated error (500 chars)
      const errorMsg = fullErrorMsg.substring(0, 500);

 // Extract selector from error (look for known prefixes in quotes)
      const selectorMatch = errorMsg.match(
        new RegExp(`['"\`]((?:${SELECTOR_PREFIXES.join('|')})[A-Z]\\w+)['"\`]`)
      );

 // Find screenshot attachment
      const screenshot = result.attachments.find(
        a => a.name === 'screenshot' && a.path
      );

 // Find trace attachment
      const trace = result.attachments.find(
        a => a.name === 'trace' && a.path
      );

 // Read diagnostics attachment (written by commonMethods fixture teardown)
      let diagnostics: DiagnosticSnapshot | null = null;
      const diagAttachment = result.attachments.find(a => a.name === 'diagnostics');
      if (diagAttachment?.body) {
        try {
          diagnostics = JSON.parse(diagAttachment.body.toString('utf-8')) as DiagnosticSnapshot;
        } catch { /* malformed -- treat as no diagnostics */ }
      }

 // Classify failure using diagnostics evidence
      const failureCategory = this.classifyFailure(fullErrorMsg, diagnostics);

 // Extract last actions from steps
      const lastActions: string[] = [];
      const steps = result.steps || [];
      const relevantSteps = steps.slice(-5);
      for (const step of relevantSteps) {
        if (step.title && !step.title.startsWith('fixture:')) {
          lastActions.push(step.title);
        }
      }

      this.failures.push({
        testName: test.title,
        file: test.location.file ? path.relative(process.cwd(), test.location.file) : 'unknown',
        error: errorMsg,
        fullError: fullErrorMsg,
        selector: selectorMatch?.[1] ?? null,
        duration: result.duration,
        screenshotPath: screenshot?.path
          ? path.relative(process.cwd(), screenshot.path)
          : null,
        tracePath: trace?.path
          ? path.relative(process.cwd(), trace.path)
          : null,
        lastActions,
        failureCategory,
        pageUrl: diagnostics?.urlHistory.at(-1) ?? '',
        workerIndex: test.parent?.project()?.metadata?.workerIndex ?? 0,
        retryAttempt: result.retry,
        consoleErrors: diagnostics?.consoleErrors ?? [],
        networkFailures: diagnostics?.networkFailures ?? [],
        pageErrors: diagnostics?.pageErrors ?? [],
        authChain: diagnostics?.authChain ?? [],
        domSnippet: (diagnostics?.domSnippet ?? '').substring(0, 10_240),
        urlBreadcrumbs: diagnostics?.urlBreadcrumbs ?? [],
        triage: null,
        bugReportId: null,
        bugHuntCategory: null,
        testIdStatus: null,
        changeSize: null,
        failureCount: getFailureCount(test.title),
      });
    }
  }

 /**
 * Classify failure into a FailureCategory using error message + diagnostic evidence.
 * Priority-ordered pattern matching per §12 RCA Protocol.
 */
  private classifyFailure(errorMsg: string, diagnostics: DiagnosticSnapshot | null): FailureCategory {
    const lower = errorMsg.toLowerCase();
    const netFails = diagnostics?.networkFailures ?? [];
    const consoleErrs = diagnostics?.consoleErrors ?? [];
    const pageErrs = diagnostics?.pageErrors ?? [];

 // P1: Auth
    if (
      lower.includes('login.microsoftonline.com') ||
      lower.includes('b2clogin.com') ||
      lower.includes('oauth') ||
      lower.includes('401') ||
      lower.includes('403') ||
      netFails.some(n => (n.url.includes('login.microsoftonline.com') || n.url.includes('b2clogin.com') || n.url.includes('oauth')) && n.status >= 400)
    ) {
      return FailureCategory.AUTH;
    }

 // P2: Network (non-auth)
    if (netFails.some(n => n.status >= 400 && !n.url.includes('login.microsoftonline.com'))) {
      return FailureCategory.NETWORK;
    }

 // P3: Selector
    const selectorPattern = new RegExp(`['"\`]((?:${SELECTOR_PREFIXES.join('|')})[A-Z]\\w+)['"\`]`);
    if (selectorPattern.test(errorMsg) || lower.includes('locator') || lower.includes('selector')) {
      return FailureCategory.SELECTOR;
    }

 // P4: Timing
    if (lower.includes('timeout') || lower.includes('waiting for')) {
      return FailureCategory.TIMING;
    }

 // P5: Infrastructure
    if (lower.includes('browser has been closed') || lower.includes('context closed') || lower.includes('target closed')) {
      return FailureCategory.INFRASTRUCTURE;
    }

 // P6: Application
    if (
      pageErrs.length > 0 ||
      consoleErrs.some(e => e.type === 'error' && (e.text.includes('unhandled') || e.text.includes('Uncaught')))
    ) {
      return FailureCategory.APPLICATION;
    }

 // P6.5: Data
    if (lower.includes('expected') && lower.includes('received') && !selectorPattern.test(errorMsg)) {
      return FailureCategory.DATA;
    }

    return FailureCategory.UNKNOWN;
  }

  onEnd(_result: FullResult): void {
 // Guard: skip write when no tests executed (e.g., grep matched nothing, aborted run).
 // Prevents clobbering last real failure data with empty {passed:0, failed:0} results.
    if (this.passedCount + this.failedCount + this.fixmeCount === 0) {
      console.log('[AgentReporter] Skipping  write -- no tests executed');
      return;
    }

    const summary: FailureSummary = {
      timestamp: new Date().toISOString(),
      failures: this.failures,
      passed: this.passedCount,
      failed: this.failedCount,
      fixme: this.fixmeCount,
      totalDuration: this.totalDuration,
      triageStats: null,
      bugReportFiles: [],
    };

 // Ensure reports directory exists
    const reportsDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    fs.writeFileSync(OUTPUT_FILE, JSON.stringify(summary, null, 2) + '\n', 'utf-8');
  }
}

export default AgentReporter;
