#!/usr/bin/env ts-node
/**
 * Queue Archival Script - Keeps agent-queue.json small by:
 * 1. Moving completed items from queue[] -> completedLog[] (stripped of injectedContext)
 * 2. Pruning completedLog entries older than --days (default: 30)
 * 3. Compacting injectedContext on active items (removes moduleContext if >500 chars)
 * 4. Reporting file size before/after
 * 
 * Usage:
 *   npm run queue:archive              # Archive completed + prune old log entries
 *   npm run queue:archive -- --days=14 # Custom retention (14 days)
 *   npm run queue:archive -- --dry-run # Preview without writing
 *   npm run queue:archive -- --compact # Also compact active item contexts
 * 
 * Exit: 0 = success, 1 = error
 */

import * as fs from 'fs';
import { QueueItem, CompletedLogEntry, QueueFile, SHARED_PATHS } from './shared-types';

const QUEUE_PATH = SHARED_PATHS.queue;
const MAX_QUEUE_FILE_KB = 500; // Warn if file exceeds this size

function getFileSizeKB(filePath: string): number {
  const stats = fs.statSync(filePath);
  return Math.round(stats.size / 1024);
}

function getCompletionDate(item: QueueItem): string {
  if (!item.history || item.history.length === 0) return new Date().toISOString();
  const last = item.history[item.history.length - 1];
  return last?.timestamp || last?.date || new Date().toISOString();
}

function archiveCompleted(queue: QueueFile, dryRun: boolean): number {
  const completed = queue.queue.filter(item => item.stage === 'completed');
  if (completed.length === 0) return 0;

  for (const item of completed) {
    const entry: CompletedLogEntry = {
      id: item.id,
      feature: item.feature ?? '',
      module: item.module,
      completedAt: getCompletionDate(item),
      archivedAt: new Date().toISOString(),
      historyLength: item.history?.length || 0,
      artifacts: item.artifacts as Record<string, string> | undefined,
      lastAction: item.history?.[item.history.length - 1]?.action,
    };
    queue.completedLog!.push(entry);
  }

  if (!dryRun) {
    queue.queue = queue.queue.filter(item => item.stage !== 'completed');
  }

  return completed.length;
}

function pruneOldLog(queue: QueueFile, retentionDays: number, dryRun: boolean): number {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - retentionDays);
  const cutoffISO = cutoff.toISOString();

  const before = queue.completedLog!.length;
  if (!dryRun) {
    queue.completedLog = queue.completedLog!.filter(
      entry => entry.archivedAt > cutoffISO
    );
  }
  const pruned = before - queue.completedLog!.filter(entry => entry.archivedAt > cutoffISO).length;
  return pruned;
}

function compactActiveContexts(queue: QueueFile, dryRun: boolean): number {
  let compacted = 0;

  for (const item of queue.queue) {
    if (!item.injectedContext) continue;

    const ctx = item.injectedContext as Record<string, unknown>;

    // Strip moduleContext if large (it's re-generated by build:context anyway)
    if (ctx.moduleContext && typeof ctx.moduleContext === 'string' && (ctx.moduleContext as string).length > 500) {
      if (!dryRun) {
        ctx.moduleContext = '(stripped -- regenerate with npm run build:context)';
      }
      compacted++;
    }

    // Strip selfAuditQuestions (static per-agent, re-injected by build:context)
    if (ctx.selfAuditQuestions && Array.isArray(ctx.selfAuditQuestions) && (ctx.selfAuditQuestions as unknown[]).length > 0) {
      if (!dryRun) {
        ctx.selfAuditQuestions = ['(stripped -- regenerate with npm run build:context)'];
      }
      compacted++;
    }

    // Strip mistake rule text (IDs are enough, full rules re-injected by build:context)
    if (ctx.mistakes && Array.isArray(ctx.mistakes) && (ctx.mistakes as unknown[]).length > 0) {
      if (!dryRun) {
        ctx.mistakes = (ctx.mistakes as Array<{ id: string }>).map(r => ({ id: r.id }));
      }
      compacted++;
    }

    // Strip learning details (IDs are enough, full entries re-injected by build:context)
    if (ctx.learnings && Array.isArray(ctx.learnings) && (ctx.learnings as unknown[]).length > 0) {
      if (!dryRun) {
        ctx.learnings = (ctx.learnings as Array<{ id: string }>).map(r => ({ id: r.id }));
      }
      compacted++;
    }

    // Strip criticalReminders (re-injected by build:context)
    if (ctx.criticalReminders && Array.isArray(ctx.criticalReminders) && (ctx.criticalReminders as unknown[]).length > 0) {
      if (!dryRun) {
        ctx.criticalReminders = ['(stripped -- regenerate with npm run build:context)'];
      }
      compacted++;
    }

    // Strip recentDefects (re-injected by build:context)
    if (ctx.recentDefects && Array.isArray(ctx.recentDefects) && (ctx.recentDefects as unknown[]).length > 0) {
      if (!dryRun) {
        ctx.recentDefects = ['(stripped -- regenerate with npm run build:context)'];
      }
      compacted++;
    }
  }

  return compacted;
}

function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const compact = args.includes('--compact');
  const daysArg = args.find(a => a.startsWith('--days='));
  const retentionDays = daysArg ? parseInt(daysArg.split('=')[1]!, 10) : 30;

  console.log('='.repeat(50));
  console.log('Queue Archival');
  console.log(`Mode: ${dryRun ? 'DRY-RUN' : 'LIVE'} | Retention: ${retentionDays} days | Compact: ${compact}`);
  console.log('='.repeat(50));

  if (!fs.existsSync(QUEUE_PATH)) {
    console.error('Queue file not found');
    process.exit(1);
  }

  const sizeBefore = getFileSizeKB(QUEUE_PATH);
  console.log(`\nFile size before: ${sizeBefore} KB`);

  const queue: QueueFile = JSON.parse(fs.readFileSync(QUEUE_PATH, 'utf-8'));
  if (!queue.completedLog) queue.completedLog = [];

  // Step 1: Archive completed items
  const archived = archiveCompleted(queue, dryRun);
  console.log(`Completed items archived: ${archived}`);

  // Step 2: Prune old log entries
  const pruned = pruneOldLog(queue, retentionDays, dryRun);
  console.log(`Old log entries pruned: ${pruned}`);

  // Step 3: Compact active contexts (optional)
  let compacted = 0;
  if (compact) {
    compacted = compactActiveContexts(queue, dryRun);
    console.log(`Active contexts compacted: ${compacted}`);
  }

  // Save
  if (!dryRun && (archived > 0 || pruned > 0 || compacted > 0)) {
    queue.lastUpdated = new Date().toISOString();
    fs.writeFileSync(QUEUE_PATH, JSON.stringify(queue, null, 2), 'utf-8');
    const sizeAfter = getFileSizeKB(QUEUE_PATH);
    console.log(`\nFile size after: ${sizeAfter} KB (saved ${sizeBefore - sizeAfter} KB)`);

    if (sizeAfter > MAX_QUEUE_FILE_KB) {
      console.warn(`\n[WARN] Queue file still exceeds ${MAX_QUEUE_FILE_KB} KB -- consider --compact or reducing history notes`);
    }
  } else if (dryRun) {
    console.log('\nDry-run -- no files modified');
  } else {
    console.log('\nNothing to archive or prune');
  }

  // Summary
  console.log(`\nQueue: ${queue.queue.length} active items | Log: ${queue.completedLog.length} archived`);
  console.log('='.repeat(50));
  process.exit(0);
}

main();
