/**
 * Selectors for the Discount Matrix page — Company Matrix tab.
 *
 * Page: Location Settings → Discount Matrix
 * Route: `/navigator/locations/{office}/settings/discount-matrix`
 * Page title: `Discount Matrix | Navigator`
 *
 * The page has three tabs:
 *   Tab 1 — "Company Matrix"        (active by default) — read-only tier grid + toolbar
 *   Tab 2 — "Region Weekly Peaks"
 *   Tab 3 — "Location Activation"
 *
 * Critical facts affecting selector use:
 *
 * 1. Tab DOM ids are auto-generated by Radix UI; their middle segment changes between
 *    renders. Never reference these auto-generated ids — select tabs by `[role="tab"]`
 *    + visible text only.
 *
 * 2. The criteria bar above the tabs has exactly 3 `[role="combobox"]` elements
 *    (Country, Currency, Business Tier) and 0 `<select>` elements. The app uses
 *    Radix comboboxes throughout.
 *
 * 3. The Company Matrix grid is ENTIRELY READ-ONLY. Measured on 2026-08-19:
 *    `tbody input` = 0, `tbody input[type=number]` = 0, `tbody [role="spinbutton"]` = 0.
 *    Editing a row opens a dialog; there are no inline cell inputs. Do not author
 *    inline-cell-input selectors for this grid.
 *
 * 4. The grid container renders before its data arrives. Waiting on the container
 *    alone will produce false "grid is empty" findings. The ready-gate must wait
 *    for a non-zero tbody row count (see ROWS).
 *
 * 5. Row lookup is content-anchored by tier range text (e.g. "0 - 1500"), never
 *    by index. Shared handlers make index-0 lookups unreliable across test runs.
 *
 * 6. No save-dialog selector is authored here. The save dialog for this tab has
 *    not been measured on this surface. See ## ASK in the ticket that produced
 *    this file — the page-object ticket will confirm whether it uses a shared
 *    dialog or a tab-specific one.
 */

// ---------------------------------------------------------------- tab navigation

/**
 * Tab 1 trigger — "Company Matrix".
 *
 * Uses :has-text (contains) rather than :text-is (exact) because the tab element
 * may contain additional child nodes (badge, icon span) whose textContent would
 * cause an exact-match to silently never resolve. "Company Matrix" is unique on
 * this page.
 */
export const TAB_COMPANY_MATRIX = '[role="tab"]:has-text("Company Matrix")';

/**
 * Tab 2 trigger — "Region Weekly Peaks".
 *
 * Uses :has-text (contains) for the same reason as TAB_COMPANY_MATRIX.
 */
export const TAB_REGION_WEEKLY_PEAKS = '[role="tab"]:has-text("Region Weekly Peaks")';

/**
 * Tab 3 trigger — "Location Activation".
 *
 * Uses :has-text (contains) for the same reason as TAB_COMPANY_MATRIX.
 */
export const TAB_LOCATION_ACTIVATION = '[role="tab"]:has-text("Location Activation")';

/** The tab list container. Waiting on this confirms the tab chrome is mounted. */
export const TAB_LIST = '[role="tablist"]';

// ---------------------------------------------------------------- criteria bar (shared above all tabs)

/**
 * Country combobox in the criteria bar.
 *
 * Anchored by the adjacent `<label>` sibling whose text is exactly "Country:".
 * The DOM structure is: `LABEL "Country:" + [role="combobox"]` inside the same
 * parent DIV — an exact adjacent-sibling match. The prior `:near()` proximity
 * selector was abandoned because it bled across controls: "Currency:" also fell
 * within the proximity radius and produced two matches in strict mode.
 * Do not hardcode "United States" — the displayed value varies by office.
 */
export const CMB_COUNTRY = 'label:text-is("Country:") + [role="combobox"]';

/**
 * Currency combobox in the criteria bar.
 *
 * Anchored by `LABEL "Currency:" + [role="combobox"]` (exact adjacent-sibling).
 * The prior `:near()` approach was abandoned because "Country:" also fell within
 * the radius, causing two matches in strict mode. Do not hardcode "USD" — the
 * displayed value depends on the selected country.
 */
export const CMB_CURRENCY = 'label:text-is("Currency:") + [role="combobox"]';

/**
 * Business Tier combobox in the criteria bar.
 *
 * Anchored by `LABEL "Business Tier:" + [role="combobox"]` (exact adjacent-sibling).
 * Uses the same deterministic technique as CMB_COUNTRY and CMB_CURRENCY for
 * consistency. Do not hardcode "Standard" — the value is user-selected at runtime.
 */
export const CMB_BUSINESS_TIER = 'label:text-is("Business Tier:") + [role="combobox"]';

/**
 * GAV Discount Threshold input in the criteria bar.
 *
 * Anchored on the field's own `name` attribute, which a live probe on 2026-08-19 confirmed
 * resolves to exactly one element. The previous placeholder anchor described the same field
 * but was weaker: a placeholder is presentational and shared far more easily than a name.
 */
export const INP_GAV_DISCOUNT_THRESHOLD = 'input[name="gavDiscountThreshold"]';

/**
 * The open listbox overlay rendered by a Radix combobox.
 *
 * Radix comboboxes render a `[role="listbox"]` in the DOM when the dropdown is open.
 * Used to detect listbox visibility and to scope option reads.
 */
export const LISTBOX = '[role="listbox"]';

/**
 * Candidate elements that would carry a validation error message if one were rendered.
 *
 * This is the exact selector list a live probe on 2026-08-19 swept across the criteria bar
 * after every input trial (valid, invalid, cleared, non-numeric). The surface produced no
 * matching element carrying error text on any input — so a non-empty result from this selector
 * is a behaviour change worth reporting.
 */
export const VALIDATION_MESSAGE_CANDIDATES =
  '[aria-live],[class*="error"],[class*="Error"],[class*="invalid"],[role="alert"]';

// ---------------------------------------------------------------- Company Matrix tab — grid

/**
 * The Company Matrix tab content panel.
 *
 * Scoped by the toolbar button text "Add Tier" which is unique to this tab panel,
 * ensuring this selector resolves to Tab 1's panel and not another tab's panel
 * during tab-switch transitions.
 */
export const PANEL_COMPANY_MATRIX = '[role="tabpanel"]:has(button:text-is("Add Tier"))';

/**
 * Body rows inside the Company Matrix grid.
 *
 * Scoped to the tab panel to avoid matching rows in other tab panels.
 */
export const ROWS = `${PANEL_COMPANY_MATRIX} tbody tr`;

/**
 * Placeholder skeleton marker present in every cell while the grid is loading.
 *
 * Before real data arrives, the grid paints 6 placeholder rows of 24 cells each.
 * Every placeholder cell contains a `div[data-slot="skeleton"]` — an animated pulse
 * element. When data arrives, the grid swaps to 9 real rows of 23 cells, and all
 * skeleton elements disappear. The presence of any match means the grid is still
 * loading; the absence of all matches (combined with at least one real row) is the
 * correct readiness signal. A non-zero row count alone is not sufficient — the 6
 * placeholder rows satisfy a row-count check in roughly 12 ms, before any data lands.
 */
export const GRID_SKELETON = `${PANEL_COMPANY_MATRIX} [data-slot="skeleton"]`;

/**
 * Column header cells in the Company Matrix grid.
 *
 * The grid thead has two rows, totalling 27 `th` elements:
 *   Row 1 — group headers (4 th): blank (colspan 2), "Non-Peak Booking Windows Days"
 *     (colspan 7), "Standard Booking Windows Days" (colspan 7), "Peak Booking Windows
 *     Days" (colspan 7).
 *   Row 2 — day-bucket headers (23 th): blank, "Revenue Tier", then three repetitions
 *     of the 7 day buckets 0-15 / 16-30 / 31-60 / 61-90 / 91-180 / 181-365 / 365+
 *     (one repetition per column group).
 * Assertions against this locator must expect 27 matches, not 22.
 */
export const COL_HEADERS = `${PANEL_COMPANY_MATRIX} thead th`;

/**
 * Returns the `tr` for a specific tier row, anchored by the tier range text.
 *
 * Row lookup is content-anchored — never by index — because shared handlers
 * make positional lookups unreliable. Use the exact tier range string as it
 * appears in the DOM, e.g. "0 - 1500" or "100001 - 20000000".
 *
 * Uses :has(td:text-is(...)) rather than :has-text(...) because has-text is a
 * substring match on the whole row's text, so a label that is a substring of
 * another row's text or of any cell in it would silently match the wrong row.
 * Content-anchored lookup must be exact; a substring match on a grid of numbers
 * will eventually collide and the failure would be silent rather than loud.
 *
 * Valid tier ranges (measured 2026-08-19):
 *   "0 - 1500" | "1501 - 3000" | "3001 - 5000" | "5001 - 15000" |
 *   "15001 - 25000" | "25001 - 50000" | "50001 - 75000" |
 *   "75001 - 100000" | "100001 - 20000000"
 */
export const rowByTierRange = (tierRange: string): string =>
  `${PANEL_COMPANY_MATRIX} tbody tr:has(td:text-is("${tierRange}"))`;

/**
 * Delete button for a specific tier row.
 *
 * The Delete button is the FIRST action button on each row (`button[title="Delete"]`);
 * scoped to the row locator returned by `rowByTierRange` to avoid cross-row collisions.
 * Caller should scope `.locator(BTN_ROW_DELETE)` on the row locator, not on the page.
 */
export const BTN_ROW_DELETE = 'button[title="Delete"]';

/**
 * Edit button for a specific tier row.
 *
 * The Edit button is the SECOND action button on each row (`button[title="Edit"]`);
 * scoped to the row locator returned by `rowByTierRange`. Clicking this opens the
 * Edit Tier dialog.
 * Caller should scope `.locator(BTN_ROW_EDIT)` on the row locator, not on the page.
 */
export const BTN_ROW_EDIT = 'button[title="Edit"]';

// ---------------------------------------------------------------- Company Matrix tab — toolbar

/**
 * "Add Tier" toolbar button.
 *
 * Scoped to the tab panel to avoid matching same-named buttons on other tabs.
 * Clicking this opens the Add Tier dialog.
 */
export const BTN_ADD_TIER = `${PANEL_COMPANY_MATRIX} button:text-is("Add Tier")`;

/**
 * "Export" toolbar button.
 *
 * Clicking this issues a POST to `/navigator/api/discount/company-matrix/export`
 * and triggers a file download. The downloaded filename follows the pattern
 * `DiscountMatrix-{country}-{currency}-{tier}.xlsx` and varies with the criteria
 * bar selection — do not hardcode any specific filename in specs.
 */
export const BTN_EXPORT = `${PANEL_COMPANY_MATRIX} button:text-is("Export")`;

/**
 * "Save" toolbar button.
 *
 * This is a page-level header control that persists the GAV Discount Threshold.
 * It is NOT inside the tab panel — measured 2026-08-19: `inTabPanel: false`,
 * ancestor is `data-slot=sidebar-inset`. The prior tab-panel-scoped selector
 * produced zero matches because Save lives outside any `[role="tabpanel"]`.
 */
export const BTN_SAVE = 'button:text-is("Save")';

// ---------------------------------------------------------------- Edit Tier dialog

/**
 * The Edit Tier dialog container.
 *
 * The dialog title renders as "Editing {tierRange}" (e.g. "Editing 0 - 1500").
 * Anchored by the word "Editing" in the dialog title so it resolves regardless
 * of which tier row triggered the open.
 */
export const DLG_EDIT_TIER = '[role="dialog"]:has-text("Editing")';

/**
 * All 21 percentage inputs inside the Edit Tier dialog.
 *
 * These inputs have no stable id and no data-testid — they are positional within
 * the dialog. Callers must use an ordered-collection approach:
 *   `page.locator(DLG_EDIT_TIER_INPUTS).nth(columnIndex)`
 * where columnIndex corresponds to the column's position in the grid (0-based,
 * left to right across all 3 column groups × 7 day buckets = 21 inputs total).
 * All inputs are `type="text"` with `inputmode="decimal"` and placeholder `0`.
 * Do not attempt to anchor individual inputs by name or id — none exist.
 */
export const DLG_EDIT_TIER_INPUTS = `${DLG_EDIT_TIER} input[inputmode="decimal"]`;

/**
 * "Cancel" button inside the Edit Tier dialog.
 *
 * Scoped to the dialog container to avoid matching same-named buttons elsewhere.
 */
export const BTN_EDIT_CANCEL = `${DLG_EDIT_TIER} button:text-is("Cancel")`;

/**
 * "Update" button inside the Edit Tier dialog.
 *
 * Scoped to the dialog container. Clicking this commits the edited percentage values.
 */
export const BTN_EDIT_UPDATE = `${DLG_EDIT_TIER} button:text-is("Update")`;

// ---------------------------------------------------------------- Add Tier dialog

/**
 * The Add Tier dialog container.
 *
 * The dialog title renders verbatim as "Adding Tier". Anchored by exact title text
 * so it does not match the Edit Tier dialog if both were ever present in the DOM.
 */
export const DLG_ADD_TIER = '[role="dialog"]:has-text("Adding Tier")';

/**
 * The "End Tier" input inside the Add Tier dialog.
 *
 * This input carries the stable author-written id `discount-matrix-tier-end`
 * (measured 2026-08-19). It is trusted as a selector anchor because it is a
 * deliberate semantic id written by the application authors, not an auto-generated
 * Radix id whose middle segment changes between renders. The Edit Tier dialog's
 * inputs have no such stable id, which is why those use a positional collection
 * (see DLG_EDIT_TIER_INPUTS). Attributes: `inputmode="numeric"`, `pattern="[0-9]*"`.
 * There is no Start Tier field — the dialog exposes only this single input.
 */
export const INP_ADD_TIER_END = '#discount-matrix-tier-end';

/**
 * "Cancel" button inside the Add Tier dialog.
 *
 * Scoped to the dialog container.
 */
export const BTN_ADD_CANCEL = `${DLG_ADD_TIER} button:text-is("Cancel")`;

/**
 * "Add Tier" confirm button inside the Add Tier dialog.
 *
 * Scoped to the dialog container. This button is disabled when the dialog first
 * opens; it becomes enabled once a valid value is entered in INP_ADD_TIER_END.
 * Use `text-is` (exact) to distinguish it from the toolbar "Add Tier" button.
 */
export const BTN_ADD_TIER_CONFIRM = `${DLG_ADD_TIER} button:text-is("Add Tier")`;
